"use client";
import {useEffect,useState} from "react";
type Logs=Record<string,number>; const GOAL=1000,KEY="sua-water-v2",HEARTS=["🤍","❤️","🧡","💛","💚","💙","💜","💕","💖","💝"];
const key=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
export default function Home(){
 const [logs,setLogs]=useState<Logs>({}),[ready,setReady]=useState(false),[customOpen,setCustomOpen]=useState(false),[custom,setCustom]=useState("150"),[effect,setEffect]=useState(0),[month,setMonth]=useState(()=>{const n=new Date();return new Date(n.getFullYear(),n.getMonth(),1)});
 const today=key(),amount=logs[today]??0,progress=Math.min(100,amount/GOAL*100);
 useEffect(()=>{try{const saved=localStorage.getItem(KEY);setLogs(saved?JSON.parse(saved):{})}catch{setLogs({})}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(logs))},[logs,ready]);
 const add=(ml:number)=>{const next=Math.min(2000,amount+ml),crossed=[1000,750,500,250].find(s=>amount<s&&next>=s);setLogs(p=>({...p,[today]:next}));if(crossed){setEffect(crossed);setTimeout(()=>setEffect(0),1400)}};
 return <main className="app-shell">
  <header className="topbar"><a className="brand" href="#today"><span>💧</span>수아의 물방울</a><nav aria-label="페이지 이동"><a href="#today">오늘</a><a href="#calendar">기록</a><a href="#rewards">스티커</a></nav></header>
  <section className="slide today-slide" id="today"><h1>수아의 물방울</h1>
   <div className={`character effect-${effect}`}><div className="orb" style={{"--fill":`${progress}%`} as React.CSSProperties}><div className="water"><i/></div><img src={amount>=GOAL?"./characters/mori-4.png":"./characters/mori-0.png"} alt="수아의 물방울 캐릭터"/>{effect>0&&<div className="milestone-burst" aria-hidden="true"><span>💧</span><span>✨</span><span>⭐</span><span>💙</span></div>}</div></div>
   <div className="tracker"><div className="amount"><b>{amount.toLocaleString()}</b><span>/ 1,000 mL</span></div><div className="bar" aria-label={`목표의 ${Math.round(progress)}%`}><i style={{width:`${progress}%`}}/></div><div className="quick">{[100,200,300].map(ml=><button key={ml} onClick={()=>add(ml)}>+{ml}mL</button>)}</div>{customOpen?<form className="custom" onSubmit={e=>{e.preventDefault();add(Number(custom)||0);setCustomOpen(false)}}><input aria-label="추가할 물의 양" autoFocus inputMode="numeric" value={custom} onChange={e=>setCustom(e.target.value)}/><span>mL</span><button>추가</button></form>:<div className="tracker-links"><button onClick={()=>setCustomOpen(true)}>직접 입력</button><button onClick={()=>{if(window.confirm("오늘 기록을 초기화할까요?"))setLogs(p=>({...p,[today]:0}))}}>초기화</button></div>}</div>
  </section>
  <Calendar logs={logs} setLogs={setLogs} month={month} setMonth={setMonth}/><Rewards amount={amount}/>
 </main>
}
function Calendar({logs,setLogs,month,setMonth}:{logs:Logs;setLogs:React.Dispatch<React.SetStateAction<Logs>>;month:Date;setMonth:(d:Date)=>void}){const y=month.getFullYear(),m=month.getMonth(),days=new Date(y,m+1,0).getDate(),offset=new Date(y,m,1).getDay(),cells=[...Array(offset).fill(null),...Array.from({length:days},(_,i)=>i+1)],prefix=`${y}-${String(m+1).padStart(2,"0")}`,entries=Object.entries(logs).filter(([d])=>d.startsWith(prefix)),total=entries.reduce((s,[,v])=>s+v,0),success=entries.filter(([,v])=>v>=GOAL).length,n=new Date(),current=y===n.getFullYear()&&m===n.getMonth(),move=(x:number)=>setMonth(new Date(y,m+x,1));return <section className="slide subpage" id="calendar"><div className="section-title"><button aria-label="이전 달" onClick={()=>move(-1)}>‹</button><h1>{y}년 {m+1}월</h1><button aria-label="다음 달" disabled={current} onClick={()=>move(1)}>›</button></div><div className="month-summary"><b>{(total/1000).toFixed(1)}L</b><span>{success}일 ⭐</span></div><div className="calendar"><div className="week">{"일월화수목금토".split("").map(d=><b key={d}>{d}</b>)}</div><div className="days">{cells.map((day,i)=>day?<Day key={i} day={day} month={month} logs={logs} setLogs={setLogs}/>:<div key={i}/>)}</div></div></section>}
function Day({day,month,logs,setLogs}:{day:number;month:Date;logs:Logs;setLogs:React.Dispatch<React.SetStateAction<Logs>>}){const date=new Date(month.getFullYear(),month.getMonth(),day),k=key(date),v=logs[k]||0,isPast=k<key();const edit=()=>{if(!isPast)return;const input=window.prompt(`${month.getMonth()+1}월 ${day}일 물 섭취량 (mL)`,String(v||""));if(input===null)return;const next=Math.min(2000,Math.max(0,Number(input)||0));setLogs(p=>({...p,[k]:next}))};return <button type="button" disabled={!isPast} onClick={edit} className={`day ${k===key()?"today":""} ${isPast?"editable":""}`} aria-label={`${month.getMonth()+1}월 ${day}일${isPast?", 기록 입력 가능":""}`}><span>{day}</span>{v>=GOAL?<i>⭐</i>:v?<i>💧</i>:null}<small>{v?`${v}mL`:isPast?"입력":""}</small></button>}
function Rewards({amount}:{amount:number}){const count=Math.min(10,Math.floor(amount/100));return <section className="slide subpage rewards" id="rewards"><h1>수아의 하트</h1><div className="sticker-count">💖 <b>{count}/10</b></div><div className="book">{HEARTS.map((heart,i)=><span className={i<count?"collected":""} key={heart}>{i<count?heart:i+1}</span>)}</div></section>}
