"use client";
import {useEffect,useRef,useState} from "react";
type Logs=Record<string,number>; const GOAL=1000,KEY="sua-water-v2";
const key=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
export default function Home(){
 const [logs,setLogs]=useState<Logs>({}),[ready,setReady]=useState(false),[customOpen,setCustomOpen]=useState(false),[custom,setCustom]=useState("150"),[effect,setEffect]=useState(0),[today,setToday]=useState(()=>key()),[month,setMonth]=useState(()=>{const n=new Date();return new Date(n.getFullYear(),n.getMonth(),1)});
 const amount=logs[today]??0,progress=Math.min(100,amount/GOAL*100);
 useEffect(()=>{try{const saved=localStorage.getItem(KEY);setLogs(saved?JSON.parse(saved):{})}catch{setLogs({})}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(logs))},[logs,ready]);
 useEffect(()=>{let timer:ReturnType<typeof setTimeout>;const schedule=()=>{const now=new Date(),midnight=new Date(now.getFullYear(),now.getMonth(),now.getDate()+1),delay=midnight.getTime()-now.getTime()+100;timer=setTimeout(()=>{setToday(key());window.dispatchEvent(new Event("sua-new-day"));schedule()},delay)};schedule();return()=>clearTimeout(timer)},[]);
 const add=(ml:number)=>{const next=Math.min(2000,amount+ml),crossed=[1000,750,500,250].find(s=>amount<s&&next>=s);setLogs(p=>({...p,[today]:next}));if(crossed){setEffect(crossed);setTimeout(()=>setEffect(0),1400)}};
 return <main className="app-shell">
  <header className="topbar"><a className="brand" href="#today"><span>💧</span>수아의 물방울</a><nav aria-label="페이지 이동"><a href="#today">오늘</a><a href="#calendar">기록</a><a href="#rewards">주사위</a></nav></header>
  <section className="slide today-slide" id="today"><h1>수아의 물방울</h1>
   <div className={`character effect-${effect}`}><div className="orb" style={{"--fill":`${progress}%`} as React.CSSProperties}><div className="water"><i/></div><img src={amount>=GOAL?"./characters/mori-4.png":"./characters/mori-0.png"} alt="수아의 물방울 캐릭터"/>{effect>0&&<div className="milestone-burst" aria-hidden="true"><span>💧</span><span>✨</span><span>⭐</span><span>💙</span></div>}</div></div>
   <div className="tracker"><div className="amount"><b>{amount.toLocaleString()}</b><span>/ 1,000 mL</span></div><div className="bar" aria-label={`목표의 ${Math.round(progress)}%`}><i style={{width:`${progress}%`}}/></div><div className="quick">{[100,200,300].map(ml=><button key={ml} onClick={()=>add(ml)}>+{ml}mL</button>)}</div>{customOpen?<form className="custom" onSubmit={e=>{e.preventDefault();add(Number(custom)||0);setCustomOpen(false)}}><input aria-label="추가할 물의 양" autoFocus inputMode="numeric" value={custom} onChange={e=>setCustom(e.target.value)}/><span>mL</span><button>추가</button></form>:<div className="tracker-links"><button onClick={()=>setCustomOpen(true)}>직접 입력</button><button onClick={()=>{if(window.confirm("오늘 물 기록과 주사위를 초기화할까요?")){setLogs(p=>({...p,[today]:0}));window.dispatchEvent(new Event("sua-reset-dice"))}}}>초기화</button></div>}</div>
  </section>
  <Calendar logs={logs} setLogs={setLogs} month={month} setMonth={setMonth}/><Rewards amount={amount}/>
 </main>
}
function Calendar({logs,setLogs,month,setMonth}:{logs:Logs;setLogs:React.Dispatch<React.SetStateAction<Logs>>;month:Date;setMonth:(d:Date)=>void}){const y=month.getFullYear(),m=month.getMonth(),days=new Date(y,m+1,0).getDate(),offset=new Date(y,m,1).getDay(),cells=[...Array(offset).fill(null),...Array.from({length:days},(_,i)=>i+1)],prefix=`${y}-${String(m+1).padStart(2,"0")}`,entries=Object.entries(logs).filter(([d])=>d.startsWith(prefix)),total=entries.reduce((s,[,v])=>s+v,0),success=entries.filter(([,v])=>v>=GOAL).length,n=new Date(),current=y===n.getFullYear()&&m===n.getMonth(),move=(x:number)=>setMonth(new Date(y,m+x,1));return <section className="slide subpage" id="calendar"><div className="section-title"><button aria-label="이전 달" onClick={()=>move(-1)}>‹</button><h1>{y}년 {m+1}월</h1><button aria-label="다음 달" disabled={current} onClick={()=>move(1)}>›</button></div><div className="month-summary"><b>{(total/1000).toFixed(1)}L</b><span>{success}일 ⭐</span></div><div className="calendar"><div className="week">{"일월화수목금토".split("").map(d=><b key={d}>{d}</b>)}</div><div className="days">{cells.map((day,i)=>day?<Day key={i} day={day} month={month} logs={logs} setLogs={setLogs}/>:<div key={i}/>)}</div></div></section>}
function Day({day,month,logs,setLogs}:{day:number;month:Date;logs:Logs;setLogs:React.Dispatch<React.SetStateAction<Logs>>}){const date=new Date(month.getFullYear(),month.getMonth(),day),k=key(date),v=logs[k]||0,isPast=k<key();const edit=()=>{if(!isPast)return;const input=window.prompt(`${month.getMonth()+1}월 ${day}일 물 섭취량 (mL)`,String(v||""));if(input===null)return;const next=Math.min(2000,Math.max(0,Number(input)||0));setLogs(p=>({...p,[k]:next}))};return <button type="button" disabled={!isPast} onClick={edit} className={`day ${k===key()?"today":""} ${isPast?"editable":""}`} aria-label={`${month.getMonth()+1}월 ${day}일${isPast?", 기록 입력 가능":""}`}><span>{day}</span>{v>=GOAL?<i>⭐</i>:v?<i>💧</i>:null}<small>{v?`${v}mL`:isPast?"입력":""}</small></button>}
const REWARDS=[
 ["▶️","출발!"],["📺","밥 먹을 때 TV 보기"],["📺","TV 많이 보기"],["🍬","젤리 1개 먹기"],["⭐","스티커 1개 붙이기"],["🍪","과자 사 먹기"],["🍦","아이스크림 먹기"],["🎲","한 번 더! 주사위 다시 굴리기"],["🕷️","아빠랑 거미 나오는 게임 하기"],["🍫","초코 과자 먹기"],["🍭","오늘의 간식 직접 고르기"],["🎲","엄마·아빠랑 보드게임 하기"],["📚","자기 전에 동화책 3권 읽기"],["🛒","마트에서 간식 1개 고르기"],["🎠","그네 타기"],["🍽️","오늘 저녁 메뉴 고르기"],["🌙","평소보다 30분 더 늦게 자기"],["🎵","원하는 노래 틀고 춤추기"],["🎁","행운의 주사위!"],["👑","황금칸! 원하는 보상 1개 고르기"]
] as const;
const ROUTE=[[10,87],[29,87],[48,87],[67,87],[86,78],[67,66],[48,66],[29,66],[10,57],[29,46],[48,46],[67,46],[86,37],[67,26],[48,26],[29,26],[10,17],[29,10],[48,10],[67,10]] as const;
const GAME_KEY="sua-dice-game-v1";
const HISTORY_KEY="sua-reward-history-v1";
type RewardResult={id:string;day:string;date:string;tile:number;dice:number;reward:string};
function Rewards({amount}:{amount:number}){const [position,setPosition]=useState(0),[used,setUsed]=useState(0),[dice,setDice]=useState<number|null>(null),[moving,setMoving]=useState(false),[rewardOpen,setRewardOpen]=useState(false),[history,setHistory]=useState<RewardResult[]>([]),moveTimer=useRef<ReturnType<typeof setTimeout>|null>(null),earned=Math.min(3,Math.floor(amount/300)),available=Math.max(0,earned-used);
 useEffect(()=>{const restore=setTimeout(()=>{try{const saved=JSON.parse(localStorage.getItem(GAME_KEY)||"{}"),isToday=saved.date===key();setPosition(isToday?Number(saved.position)||0:0);setUsed(isToday?Number(saved.used)||0:0);if(!isToday)localStorage.setItem(GAME_KEY,JSON.stringify({position:0,used:0,date:key()}))}catch{/* 손상된 저장 데이터는 새 게임으로 시작 */}},0);return()=>clearTimeout(restore)},[]);
 useEffect(()=>{const restore=setTimeout(()=>{try{const today=key(),saved=(JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]") as RewardResult[]).filter(item=>item.day===today);setHistory(saved);localStorage.setItem(HISTORY_KEY,JSON.stringify(saved))}catch{setHistory([])}},0);return()=>clearTimeout(restore)},[]);
 useEffect(()=>()=>{if(moveTimer.current)clearTimeout(moveTimer.current)},[]);
 useEffect(()=>{const resetDice=()=>{if(moveTimer.current)clearTimeout(moveTimer.current);setPosition(0);setUsed(0);setDice(null);setMoving(false);setRewardOpen(false);localStorage.setItem(GAME_KEY,JSON.stringify({position:0,used:0,date:key()}))};window.addEventListener("sua-reset-dice",resetDice);return()=>window.removeEventListener("sua-reset-dice",resetDice)},[]);
 useEffect(()=>{const startNewDay=()=>{if(moveTimer.current)clearTimeout(moveTimer.current);setPosition(0);setUsed(0);setDice(null);setMoving(false);setRewardOpen(false);setHistory([]);localStorage.setItem(GAME_KEY,JSON.stringify({position:0,used:0,date:key()}));localStorage.removeItem(HISTORY_KEY)};window.addEventListener("sua-new-day",startNewDay);return()=>window.removeEventListener("sua-new-day",startNewDay)},[]);
 const save=(nextPosition:number,nextUsed:number)=>localStorage.setItem(GAME_KEY,JSON.stringify({position:nextPosition,used:nextUsed,date:key()}));
 const roll=()=>{if(!available||moving)return;const result=Math.floor(Math.random()*6)+1,nextUsed=used+1;setRewardOpen(false);setDice(result);setUsed(nextUsed);setMoving(true);let step=0,current=position;const move=()=>{current=Math.min(19,current+1);step++;setPosition(current);if(step<result&&current<19)moveTimer.current=setTimeout(move,380);else{const finalUsed=current===7?Math.max(0,nextUsed-1):nextUsed;setUsed(finalUsed);setMoving(false);setRewardOpen(true);save(current,finalUsed);const entry:RewardResult={id:`${Date.now()}-${current}`,day:key(),date:new Date().toLocaleString("ko-KR",{hour:"2-digit",minute:"2-digit"}),tile:current+1,dice:result,reward:REWARDS[current][1]};setHistory(previous=>{const next=[entry,...previous.filter(item=>item.day===key())];localStorage.setItem(HISTORY_KEY,JSON.stringify(next));return next})}};moveTimer.current=setTimeout(move,180)};
 const routePoints=ROUTE.map(([x,y])=>`${x},${y}`).join(" ");
 return <section className="slide subpage rewards" id="rewards"><div className="game-shell"><div className="game-stage"><div className="board-wallet">🎲 <b>{available}</b><small>남은 주사위</small></div><svg className="route-line" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><polyline className="route-shadow" points={routePoints}/><polyline className="route-road" points={routePoints}/><polyline className="route-guide" points={routePoints}/></svg>{REWARDS.map(([,reward],i)=>{const [x,y]=ROUTE[i],size=reward.length<=7?"tile-short":reward.length<=13?"tile-medium":"tile-long";return <div className={`route-tile ${size} tone-${i%4} ${i===7||i===18?"special":""} ${i===19?"finish":""}`} style={{left:`${x}%`,top:`${y}%`}} aria-label={`${i+1}번 칸, ${reward}`} key={reward}><small>{i+1}</small><strong>{reward}</strong></div>})}<img className={`route-token ${moving?"hopping":""}`} style={{left:`${ROUTE[position][0]}%`,top:`${ROUTE[position][1]}%`}} src="./characters/mori-4.png" alt={`현재 ${position+1}번 칸에 있는 모리`}/>{rewardOpen&&<div className="reward-pop" role="dialog" aria-modal="true" aria-label="도착 보상"><button onClick={()=>setRewardOpen(false)} aria-label="닫기">×</button><small>{position+1}번 칸 도착!</small><strong>{REWARDS[position][1]}</strong></div>}</div><footer className="game-dock"><div className={`die ${moving?"rolling":""}`} aria-live="polite">{dice??"?"}</div><div><b>{moving?`${dice}칸 이동 중!`:dice?`${dice}이 나왔어요!`:"주사위를 굴려 보세요!"}</b><small>물 300mL마다 주사위가 하나 생겨요. 하루 최대 3개!</small></div><button onClick={roll} disabled={!available||moving}>{moving?"이동 중…":available?"주사위 굴리기":"주사위 모으는 중"}</button></footer><section className="reward-history" aria-labelledby="reward-history-title"><div className="history-head"><div><small>오늘의 주사위 결과</small><h2 id="reward-history-title">오늘 받은 보상</h2></div>{history.length>0&&<button onClick={()=>{if(window.confirm("오늘 받은 보상 기록을 지울까요?")){setHistory([]);localStorage.removeItem(HISTORY_KEY)}}}>기록 지우기</button>}</div>{history.length?<div className="history-list">{history.map(item=><article key={item.id}><span>{item.tile}</span><div><strong>{item.reward}</strong><small>{item.date} · 주사위 {item.dice}</small></div></article>)}</div>:<div className="history-empty">오늘 받은 보상이 아직 없어요.<br/>주사위를 굴리면 여기에 저장돼요!</div>}</section></div></section>}
