"use client";
import {useEffect,useState} from "react";
type Logs=Record<string,number>; type Tab="today"|"calendar"|"rewards";
const GOAL=1000, KEY="mori-water-v1", steps=[250,500,750,1000];
const key=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
function demo(){const n=new Date(),vals=[1000,850,1000,600,1000,950,1000,700,1000,400,900,1000,750,1000];return Object.fromEntries(vals.map((v,i)=>[key(new Date(n.getFullYear(),n.getMonth(),Math.max(1,n.getDate()-i-1))),v]));}
export default function Home(){
 const [tab,setTab]=useState<Tab>("today"),[logs,setLogs]=useState<Logs>({}),[ready,setReady]=useState(false),[customOpen,setCustomOpen]=useState(false),[custom,setCustom]=useState("150"),[celebrate,setCelebrate]=useState(false);
 const today=key(),amount=logs[today]??0,progress=Math.min(100,amount/GOAL*100),now=new Date();
 useEffect(()=>{try{const s=localStorage.getItem(KEY);setLogs(s?JSON.parse(s):demo())}catch{setLogs(demo())}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(logs))},[logs,ready]);
 const add=(ml:number)=>{const next=Math.min(2000,amount+ml);setLogs(p=>({...p,[today]:next}));if(steps.some(m=>amount<m&&next>=m)){setCelebrate(true);setTimeout(()=>setCelebrate(false),1800)}};
 const complete=Object.values(logs).filter(v=>v>=GOAL).length, month=key(now).slice(0,7),entries=Object.entries(logs).filter(([d])=>d.startsWith(month)),total=entries.reduce((s,[,v])=>s+v,0),success=entries.filter(([,v])=>v>=GOAL).length;
 return <main className="app-shell">
  {celebrate&&<div className="confetti" aria-live="polite"><span>💧</span><span>⭐</span><span>🎉</span><b>참 잘했어요!</b></div>}
  <header className="topbar"><button className="brand" onClick={()=>setTab("today")}><span>💧</span>모리의 물방울</button><div className="date"><span>☀️</span><div><small>오늘도 촉촉하게!</small><b>{now.getMonth()+1}월 {now.getDate()}일</b></div></div></header>
  {tab==="today"&&<section className="today-grid">
   <div className="hero-copy"><label>오늘의 물 마시기</label><h1>모리와 함께<br/><em>물방울을 채워봐!</em></h1><p>한 모금씩 마실 때마다 모리가 더 신나요.<br/>오늘도 목표까지 즐겁게 가볼까요?</p><div className="streak">🔥 <b>{Math.min(complete,7)}일 연속</b><small>정말 멋져요!</small></div></div>
   <div className="character"><div className="orb" style={{"--fill":`${progress}%`} as React.CSSProperties}><div className="water"><i/></div><img src="/mori-otter.png" alt="물컵을 든 수달 캐릭터 모리"/></div><div className="speech">{amount>=GOAL?"우와, 오늘 목표 성공!":amount>=500?"절반 넘었어! 조금만 더!":"한 모금 마셔볼까?"}</div><span className="float one">💧</span><span className="float two">✨</span></div>
   <div className="tracker"><div className="amount"><div><b>{amount.toLocaleString()}</b> mL</div><small>목표 1,000mL</small></div><div className="bar"><i style={{width:`${progress}%`}}/></div><div className="steps">{steps.map(m=><span className={amount>=m?"on":""} key={m}><i>{amount>=m?"★":"○"}</i>{m===1000?"완료":`${m}mL`}</span>)}</div><p className="remain">{amount>=GOAL?"오늘의 목표를 모두 채웠어요! 🎉":<><b>{GOAL-amount}mL</b>만 더 마시면 오늘 목표 달성!</>}</p><div className="quick">{[100,200,300].map((ml,i)=><button key={ml} onClick={()=>add(ml)}>＋ {ml}mL<small>{["작은 컵","보통 컵","큰 컵"][i]}</small></button>)}</div>{customOpen?<form className="custom" onSubmit={e=>{e.preventDefault();add(Number(custom)||0);setCustomOpen(false)}}><input autoFocus inputMode="numeric" value={custom} onChange={e=>setCustom(e.target.value)}/><span>mL</span><button>추가하기</button></form>:<button className="custom-link" onClick={()=>setCustomOpen(true)}>직접 입력하기</button>}</div>
   <div className="reward-strip"><span>🎁</span><div><small>오늘의 보상</small><b>{amount>=GOAL?"반짝별 스티커를 받았어요!":"목표를 달성하면 스티커를 받아요!"}</b></div><div className="preview"><span className={amount>=GOAL?"earned":""}>⭐</span><small>{amount>=GOAL?"획득 완료":"1000mL에 열려요"}</small></div></div>
  </section>}
  {tab==="calendar"&&<Calendar logs={logs} total={total} success={success}/>} {tab==="rewards"&&<Rewards stickers={complete}/>} 
  <nav><button className={tab==="today"?"active":""} onClick={()=>setTab("today")}><span>💧</span>오늘</button><button className={tab==="calendar"?"active":""} onClick={()=>setTab("calendar")}><span>▣</span>기록</button><button className={tab==="rewards"?"active":""} onClick={()=>setTab("rewards")}><span>★</span>스티커</button></nav>
 </main>
}
function Calendar({logs,total,success}:{logs:Logs,total:number,success:number}){const n=new Date(),days=new Date(n.getFullYear(),n.getMonth()+1,0).getDate(),offset=new Date(n.getFullYear(),n.getMonth(),1).getDay(),cells=[...Array(offset).fill(null),...Array.from({length:days},(_,i)=>i+1)];return <section className="subpage"><div className="heading"><div><label>매일매일 쌓이는 건강 습관</label><h1>{n.getMonth()+1}월의 물방울 기록</h1></div><div className="summary"><b>{(total/1000).toFixed(1)}L</b><small>이번 달 마신 물</small></div></div><div className="stats"><article>🏆<b>{success}일</b><small>목표 달성</small></article><article>💧<b>{Math.round(total/Math.max(1,n.getDate()))}mL</b><small>하루 평균</small></article><article>⭐<b>{success}개</b><small>모은 스티커</small></article></div><div className="calendar"><div className="week">{"일월화수목금토".split("").map(x=><b key={x}>{x}</b>)}</div><div className="days">{cells.map((day,i)=>day?<Day key={i} day={day} n={n} logs={logs}/>:<div key={i}/>)}</div></div></section>}
function Day({day,n,logs}:{day:number,n:Date,logs:Logs}){const k=key(new Date(n.getFullYear(),n.getMonth(),day)),v=logs[k]||0;return <div className={`day ${k===key()?"today":""}`}><span>{day}</span>{v>=GOAL?<i>⭐</i>:v?<i>💧</i>:null}<small>{v?`${v}mL`:""}</small></div>}
function Rewards({stickers}:{stickers:number}){const items=[["🍦","아이스크림 데이트",7],["🎬","영화 고르기",12],["🧸","깜짝 선물",20]] as const;return <section className="subpage"><div className="heading"><div><label>참 잘했어요!</label><h1>모리의 스티커 보물함</h1><p>물을 1L 다 마신 날마다 반짝별 하나가 쌓여요.</p></div><div className="summary"><span>⭐</span><b>{stickers}</b><small>내 스티커</small></div></div><div className="book"><h2>이번 달 스티커판</h2><div>{Array.from({length:20},(_,i)=><span className={i<stickers?"collected":""} key={i}>{i<stickers?"⭐":i+1}</span>)}</div></div><h2>스티커로 바꿀 수 있어요</h2><div className="shop">{items.map(r=><article key={r[1]}><span>{r[0]}</span><div><b>{r[1]}</b><small>⭐ {r[2]}개</small></div><button disabled={stickers<r[2]}>{stickers>=r[2]?"바꾸기":`${r[2]-stickers}개 더`}</button></article>)}</div></section>}
